# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
    extraModprobeConfig = ''
      blacklist hid_sensor_hub
    '';
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = ["defaults" "size=2G" "mode=755"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/1562-7E09";
      fsType = "vfat";
    };

    "/nix" = {
      device = "zpool/nix";
      fsType = "zfs";
    };

    "/persist" = {
      device = "zpool/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/persist/home" = {
      device = "zpool/persist/home";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/etc/ssh" = {
      device = "/persist/etc/ssh";
      neededForBoot = true;
      options = ["bind"];
    };
  };

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  swapDevices = [];
}
